### ISSUE TITLE
Informative error-checking

### ISSUE THREAD

**Issue by raphaelmazor** [SCCWRP/PHAB#2]
It looks like some of the error checking I had in the script I sent you is working in the function. We should probably remove this functionality, and instead return error messages. These are roughly in sequential order.

1. Missing fields in stations or GIS. Indicate if any required columns are entirely missing from either data inputs: "Required fields are missing from XXX dataframe:" (return list of missing fields)
Required stations fields:
c("StationCode", "MAX_ELEV", "AREA_SQKM", "ELEV_RANGE", "MEANP_WS", "New_Long", "SITE_ELEV", "KFCT_AVE", "New_Lat", "MINP_WS", "PPT_00_09")
Required phab fields:
c("StationCode","SampleDate","PHAB_SampleID", "Variable","Result","Count_Calc")

2. Stations missing
Check to see that the stations match in the two input data frames, and return an appropriate error message and list of stations.

3. Duplicated stations
Look for duplicated stations in the stations data frame. Return an error message indicating which stations are duplicated.

4. Missing PHAB data.
Note that because phab data is in "long" format, we have to do more than check for field names like in #1. Return a dataframe of StationCode, SampleID, and missing phab variable.
Required PHAB variables:
c("XSLOPE", "XBKF_W", "H_AqHab", "PCT_SAFN", "XCMG", "Ev_FlowHab", "H_SubNat", "XC", "PCT_POOL", "XFC_ALG", "PCT_SA", "PCT_RC")

5. Excess PHAB data:
If any sample has more than one result for a single phab variable, return a dataframe indicating the problem.

6. Bad values
We should return error messages if any predictor data are negative (except for New_Long)
Ditto for all phab variables
The following variables should also be greater than zero: 
XBKF_W
H_Aq_Hab
Ev_FlowHab
H_SubNat

**Comment by fawda123** [comment]
1 - 5 9a40d5d98ff8791c449633c40c64e229cf5519b5

**Comment by fawda123** [comment]
6 - 17f8a6b25e86e4e259efc002f2b5d0398aff83f4
